# Copyright (c) 2025, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "common-agent-helm.resource.prefix" . }}-common-agent-deployment
  labels:
    app.kubernetes.io/app: "apim-common-agent"
    helm.sh/chart: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/app: "apim-common-agent"
      app.kubernetes.io/name: {{ template "common-agent-helm.resource.prefix" . }}-common-deployment
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/app: "apim-common-agent"
        app.kubernetes.io/name: {{ template "common-agent-helm.resource.prefix" . }}-common-deployment
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/log-conf.yaml") . | sha256sum }}
    spec:
      serviceAccountName: wso2agent-platform
      containers:
        - name: {{ template "common-agent-helm.resource.prefix" . }}-common-deployment
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.agent.debug }}
          command: ["dlv"]
          args:
            - "exec"
            - "./apim-common-agent"
            - "--headless"
            - "--listen=:2345"
            - "--api-version=2"
            - "--accept-multiclient"
            - "--log"
          {{- end }}

          ports:
            - name: grpc-port
              containerPort: 18000
            - name: rest-port
              containerPort: 18001
            {{ if and .Values.metrics .Values.metrics.enabled}}
            - containerPort: 18006
              protocol: "TCP"
            {{ end }}
            {{- if .Values.agent.debug }}
            - containerPort: 2345
              name: "debug-port"
            {{- end }}
          env:
            - name: APIM_AGENT_NAME
              value: {{ .Values.agent.gateway }}
            - name: APIM_AGENT_PRIVATE_KEY_PATH
              value: /home/wso2/security/keystore/common-agent.key
            - name: APIM_AGENT_PUBLIC_CERT_PATH
              value: /home/wso2/security/keystore/common-agent.crt
            - name: APIM_AGENT_SERVER_NAME
              value: {{ .Values.service.name }}.{{ .Release.Namespace }}.svc
            - name: APIM_AGENT_GRPC_PORT
              value: "18000"
            {{- $certs := .Values.controlPlane.certificates | default (dict) }}
            - name: CA_CERT_SECRET_NAME
              value: {{ default "apim-ca-certificate" $certs.caCertSecretName | quote }}
          volumeMounts:
            - name: log-conf-volume
              mountPath: /home/wso2/conf/
            - name: common-agent-certificates
              mountPath: /home/wso2/security/keystore/common-agent.key
              subPath: tls.key
            - name: common-agent-certificates
              mountPath: /home/wso2/security/keystore/common-agent.crt
              subPath: tls.crt
            - name: common-agent-certificates
              mountPath: /home/wso2/security/truststore/common-agent-ca.crt
              subPath: ca.crt
          {{- if not .Values.agent.debug }}
          readinessProbe:
            exec:
              command: [ "sh", "check_health.sh" ]
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 5
          livenessProbe:
            exec:
              command: [ "sh", "check_health.sh" ]
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 5
          {{- end }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory | default "128Mi" }}
              cpu: {{ .Values.resources.requests.cpu | default "100m" }}
            limits:
              memory: {{ .Values.resources.limits.memory | default "256Mi" }}
              cpu: {{ .Values.resources.limits.cpu | default "200m" }}
      {{- if and .Values.wso2.subscription .Values.wso2.subscription.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.wso2.subscription.imagePullSecrets }}
      {{ end }}
      volumes:
        - name: log-conf-volume
          configMap:
            name: {{ .Release.Name }}-log-conf
        - name: common-agent-certificates
          secret:
            secretName: {{ if .Values.certificates }}{{ .Values.certificates.serverCertSecretName | default "common-agent-server-cert" }}{{ else }}"common-agent-server-cert"{{ end }}
